return {
  "williamboman/mason.nvim",
  opts = {
    ensure_installed = {
      "codelldb",
      "css-lsp",
      "docker-compose-language-service",
      "dockerfile-language-server",
      "eslint-lsp",
      "hadolint",
      "helm-ls",
      "json-lsp",
      "lua-language-server",
      "markdown-toc",
      "markdownlint",
      "marksman",
      "prettier",
      "pyright",
      "ruff-lsp",
      "shfmt",
      "sqlfluff",
      "stylua",
      "svelte-language-server",
      "taplo",
      "vtsls",
      "yaml-language-server",
    },
  },
}
